// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Params_Rank","status":true,"description":"能力値を非表示にしたりランク表示にします。","parameters":{"Flag":"on","OP_FontSize":"28","Params_FontSize":"28","Params":"atk def mat mdf agi luk","ATK":"0 20 30 40 50 60 70 80 90 100 110 120 130 140 150 160 170 180 200","ATK_Rank":"F E- E E+ D- D D+ C- C C+ B- B B+ A- A A+ S- S S+","DEF":"0 20 30 40 50 60 70 80 90 100 110 120 130 140 150 160 170 180 200","DEF_Rank":"F E- E E+ D- D D+ C- C C+ B- B B+ A- A A+ S- S S+","MAT":"0 20 30 40 50 60 70 80 90 100 110 120 130 140 150 160 170 180 200","MAT_Rank":"F E- E E+ D- D D+ C- C C+ B- B B+ A- A A+ S- S S+","MDF":"0 20 30 40 50 60 70 80 90 100 110 120 130 140 150 160 170 180 200","MDF_Rank":"F E- E E+ D- D D+ C- C C+ B- B B+ A- A A+ S- S S+","AGI":"0 20 30 40 50 60 70 80 90 100 110 120 130 140 150 160 170 180 200","AGI_Rank":"F E- E E+ D- D D+ C- C C+ B- B B+ A- A A+ S- S S+","LUK":"0 20 30 40 50 60 70 80 90 100 110 120 130 140 150 160 170 180 200","LUK_Rank":"F E- E E+ D- D D+ C- C C+ B- B B+ A- A A+ S- S S+","HP_Flag":"off","HP":"？？？","MP_Flag":"off","MP":"？？？","TP_Flag":"off","TP":"？？？"}}
];
